/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./app/**/*.{js,ts,jsx,tsx,mdx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container": "#201f20",
        "on-secondary-container": "#b6b5b4",
        surface: "#131314",
        background: "#131314",
        "surface-tint": "#ffb4aa",
        secondary: "#c8c6c6",
        "primary-container": "#ff5545",
        "primary-fixed-dim": "#ffb4aa",
        error: "#ffb4ab",
        tertiary: "#ffb3ac",
        "on-secondary": "#303030",
        "on-surface-variant": "#e4beb9",
        "secondary-fixed": "#e4e2e1",
        "outline-variant": "#5b403d",
        primary: "#ffb4aa",
        "on-surface": "#e5e2e3",
        "inverse-primary": "#c0000a",
        "on-primary-container": "#5c0002",
        "on-error": "#690005",
        "surface-bright": "#3a393a",
        "error-container": "#93000a",
        "surface-container-highest": "#353436",
        "inverse-surface": "#e5e2e3",
        "on-background": "#e5e2e3",
        "inverse-on-surface": "#313031",
        "secondary-container": "#474747",
        "surface-container-lowest": "#0e0e0f",
        "on-tertiary": "#680008",
        "surface-variant": "#353436",
        "tertiary-container": "#ff544e",
        "surface-container-low": "#1c1b1c",
        "surface-dim": "#131314",
        "on-primary-fixed": "#410001",
        "on-primary": "#690003",
        outline: "#ab8985",
        "primary-fixed": "#ffdad5",
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
}
